services:
  - type: web
    name: iihf-fantasy-backend
    env: python
    buildCommand: apt-get install -y chromium-browser && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CHAMPIONSHIP_URL
        value: https://www.iihf.com/en/events/2026/wm
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser
